### ISSUE TITLE
BuildProject ：CMakeset_target_properties Can not find target to add properties to: IrrXML

### ISSUE THREAD

**Issue by jaggerjiang** [vilbeyli/VQE#133]
CMake Error at CMakeLists.txt:193 (set_target_properties):
  set_target_properties Can not find target to add properties to: IrrXML

CMake Error at CMakeLists.txt:194 (set_target_properties):
  set_target_properties Can not find target to add properties to: uninstall

**Comment by vilbeyli** [comment]
Are submodules synced?

`git submodule update --init --recursive`

Assuming you've solved it, closing the issue. 
Please feel free to reopen if the issue is not fixed.
